source 'https://rubygems.org'
ruby '2.1.6'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sendgrid_ruby'
gem 'dotenv'
#gem 'sendgrid4r'
#gem 'sinatra-rocketio'
gem 'thin'
gem 'pusher'
#gem 'mongo'
#gem 'bson_ext'
group :test do
#  gem 'rspec'
#  gem 'rack-test'
end
